enum TemperatureUnit {
  CELSIUS
  FAHRENHEIT
}

type Temperature {
  value: Float
  unit: TemperatureUnit
}

type Zone {
  name: String!
  temperature: Temperature
  humidity: Float
}

type Query {
  allZones: [Zone!]
}